name: Database Migrations
on:
  push:
    branches:
      - release
  workflow_dispatch: # Allows manual triggering
jobs:
  migrate:
    name: Run Database Migrations
    runs-on: ubuntu-latest-custom
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Apply database migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
        run: |
          cd packages/db
          npx prisma migrate deploy